### PR TITLE
Adding Pyimagej Notebook

### PR DESCRIPTION
**Pull request by JenuC**
-  Added a python notebook for accessing flimlib functions (uses python libraries : pyimagej, sdtfile)
-  Added a proper spcm _cells.sdt_ file with compression

### CODE REVIEW

**Comment by ctrueden** [comment]
As part of merging this, I'll make sure we have a new release of pyimagej with a consistent dependency stack including pyjnius 1.3.0, so that calls to ImageJ Ops from Python work properly.

**Comment by Xanthorapedia** [comment]
> As part of merging this, I'll make sure we have a new release of pyimagej with a consistent dependency stack including pyjnius 1.3.0, so that calls to ImageJ Ops from Python work properly.

@ctrueden Do you think that's the case already?

**Comment by ctrueden** [comment]
@hinerm Can you please look at this once the PyImageJ stack has been converted to JPype? Maybe calling Ops (particularly the `ops.run(String, Object...)` method with varargs) works better with JPype than it does with PyJNIus?

**Comment by JenuC** [comment]
I checked out the JPype ops:  
`ij.op().help("flim.fitLMA")` looks good.  however, I am at an impasse trying to realize the best way to initialize `flim.flimlib.flimj.FitParams` object from python.  please advise. @ctrueden

**Comment by JenuC** [comment]
I used `imagej.sj.jclass('flimlib.flimj.FitParams').newInstance()` for initializing the class. 
Not sure if that is the right way, but it works. :)

**Comment by Xanthorapedia** [comment]
Thanks @JenuC for the hard work! The notebook looks awesome with working PyImageJ calls! 😃 

> I used `imagej.sj.jclass('flimlib.flimj.FitParams').newInstance()` for initializing the class.
> Not sure if that is the right way, but it works. :)

Perhaps a little more idiomatic way would be to use `imagej.sj.jimport()` followed by a conventional constructor call, as in [scijava/scyjava](https://github.com/scijava/scyjava#use-java-classes-from-python)? Just a suggestion. We can merge as soon as you are satisfied.

**Comment by ctrueden** [comment]
I agree with @Xanthorapedia. You can write:
```python
FitParams = imagej.sj.jclass('flimlib.flimj.FitParams')
fitParams = FitParams()
```
If the `newInstance` calls can be changed as above, we can get this merged! :+1:

**Comment by JenuC** [comment]
I changed the notebook to
```python
FitParams = imagej.sj.jclass('flimlib.flimj.FitParams')
fitParams = FitParams.newInstance()
```
I could not call FitParams(), am I missing something?

**Comment by ctrueden** [comment]
Sorry @JenuC, I made a typo above. As @Xanthorapedia said, it should be `jimport`, not `jclass`. I edited the above post to correct it. Try again, please?

**Comment by JenuC** [comment]
@ctrueden : That worked. updated the notebook with ```jimport```

**Comment by Xanthorapedia** [comment]
Thanks @JenuC. That looks great! Just one more question: Is there a specific reason we use `sdtfile` instead of an ImageJ opener (probably [`ij.io().open()`](https://github.com/imagej/pyimagej#usage) but I'm not sure if that works with `numpy` etc.)? Can you probably add that if it doesn't take too much effort? Just in case someone is working with a different format.

**Comment by JenuC** [comment]
Sdtfile handles sdt files better and supports latest formats. Let's just go with sdtfile for now.

**Comment by JenuC** [comment]
The notebook is a demonstration with the sample data in the repo, this version is acceptable. There is more pyimagej works going on in the lab. I dont want this notebook to overlap with those.

**Comment by Xanthorapedia** [comment]
@JenuC Sounds good. Merged.

**Pull request merged**
